/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BlogItem {
    'idPost': string;
    'resume': string;
    'timestamp': Date;
    'titlepost': string;
  }
  interface BlogItemAttributes extends StencilHTMLAttributes {
    'idPost'?: string;
    'onOnClickEvent'?: (event: CustomEvent) => void;
    'resume'?: string;
    'timestamp'?: Date;
    'titlepost'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BlogItem': Components.BlogItem;
  }

  interface StencilIntrinsicElements {
    'blog-item': Components.BlogItemAttributes;
  }


  interface HTMLBlogItemElement extends Components.BlogItem, HTMLStencilElement {}
  var HTMLBlogItemElement: {
    prototype: HTMLBlogItemElement;
    new (): HTMLBlogItemElement;
  };

  interface HTMLElementTagNameMap {
    'blog-item': HTMLBlogItemElement
  }

  interface ElementTagNameMap {
    'blog-item': HTMLBlogItemElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
